defaults: &defaults
  adapter: mysql
  encoding: utf8
  username: lbl
  password: lbl
  host: localhost

development:
  database: lbl_development
  <<: *defaults

test:
  database: lbl_test
  <<: *defaults

production:
  database: lbl_production
  <<: *defaults
  
rake:
  database: bukingz_test
  <<: *defaults